### ISSUE TITLE
server connection drop-down

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/fusion-studio#38]
after creating a connection to a running server 7 out of 10 times the dropdown menu cannot be activated, instead of the dropdown the `add a new connection pop-up menu` comes up. i m stuck in a loop. 

This is on a second run of fusion-d server on macOS 10.14.5. 
![Screenshot 2019-06-10 at 13 18 04](https://user-images.githubusercontent.com/6205362/59192291-415af480-8b82-11e9-8f1a-f74e12e130b5.png)

see the [failed tests](https://travis-ci.com/evolvedbinary/fusion-studio-extension/jobs/206512344)

**Comment by ccheraa** [comment]
Problem already fixed
