### ISSUE TITLE
--no-sandbox option required on linux to run FusionStudio

### ISSUE THREAD

**Issue by gmella** [evolvedbinary/fusion-studio#82]
...at least on my debian (9.13) using fusion-studio-1.0.3.deb package file.

I get :
```
$ fusion-studio-electron 
Trace/breakpoint trap
```

Add --no-sandbox option works arround.

Maybe related to my FR locale ? not sure...

Regards,

**Comment by adamretter** [comment]
@ccheraa can you take a look please?
